services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    user: 1000:1000 # uid:gid
    group_add:
      - "993" # getent group render | cut -d: -f3
      - "44" # getent group video | cut -d: -f3
    devices:
        - /dev/dri/:/dev/dri/
        # - /dev/kfd:/dev/kfd # Remove this device if you don't use the OpenCL tone-mapping
    environment:
        JELLYFIN_PublishedServerUrl: http://server.home:8096 # Optional - alternative address used for autodiscovery
        ROC_ENABLE_PRE_VEGA: 1
    network_mode: 'host'
    volumes:
      - ${HOME}/apps/jellyfin/config:/config
      - ${HOME}/apps/jellyfin/cache:/cache
      - ${HOME}/Media:/media
      - "/mnt/disk1/Media:/mnt/disk1/Media" # mount symbolic links
      - "/mnt/disk2/TV Shows:/mnt/disk2/TV Shows" # mount symlinked directory to avoid issues with docker bind mounts
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
        - host.docker.internal:host-gateway

networks:
    default:
        external: true
        name: main
