---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - WEBUI_PORT=8446
    volumes:
        - ${HOME}/apps/qbittorrent/config:/config
        - ${HOME}/Media:/data
        - ${HOME}/Downloads/torrents:/torrents
    network_mode: host
#    ports:
#      - 8446:8446
#      - 6881:6881
#      - 6881:6881/udp
    restart: unless-stopped

networks:
  default:
    external: true
    name: main
