#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr_v1:
    container_name: homarr_v1
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${HOME}/apps/homarr_v1/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=def0378b9696e34fb0cf9f13c238f676979376152525e68567b1d621afac1102
    ports:
      - '82:7575'

  dash:
    image: mauricenino/dashdot:latest
    container_name: homarr-dash
    ports:
      - '3001:3001'
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/mnt/host:ro

networks:
  default:
    external: true
    name: main
