services:
  adguard-home:
    image: adguard/adguardhome
    container_name: adguard-home
    hostname: adguard-home
    restart: unless-stopped
    volumes:
      - ${HOME}/apps/adguard/opt/adguardhome/work:/opt/adguardhome/work
      - ${HOME}/apps/adguard/opt/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - 192.168.1.200:53:53/udp
      - 192.168.1.200:53:53/tcp
      - 3000:3000
