services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - nginx-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    # environment:
    #   DB_MYSQL_HOST: "db"
    #   DB_MYSQL_PORT: 3306
    #   DB_MYSQL_USER: ${DB_USER}
    #   DB_MYSQL_PASSWORD: ${DB_PASSWORD}
    #   DB_MYSQL_NAME: "npm"
    volumes:
      - ${HOME}/apps/npm/data:/data
      - ${HOME}/apps/npm/etc/letsencrypt:/etc/letsencrypt
    # depends_on:
    #   - db

  # db:
  #   image: 'jc21/mariadb-aria:latest'
  #   restart: unless-stopped
  #   networks:
  #     - nginx-proxy
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: 'npm'
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - /home/ahmed/apps/npm/mysql:/var/lib/mysql

networks:
  nginx-proxy:
    external: true
    name: main
