services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/apps/ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 'count: all' uses all available GPUs. You can specify a number (e.g., 1) for a specific one.
              count: all
              capabilities: ["gpu"]


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3002:8080"
    volumes:
      - /opt/ai-apps/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped

  openedai-speech:
      image: ghcr.io/matatonic/openedai-speech-min
      container_name: openedai-speech
      volumes:
        - ${HOME}/apps/openedai/voices:/app/voices
        - ${HOME}/apps/openedai/config:/app/config

networks:
  default:
    external: true
    name: main
